// @generated by cargo run -p ygg-cli --bin generate-sdks
// Rust client methods generated from docs/spec/v1/schemas/methods/.
use anyhow::Result;
use crate::client::KernelClient;
use crate::types::*;
impl KernelClient {
    pub async fn asset_get(&self, params: AssetGetParams) -> Result<AssetGetResponse> {
        let raw = self
            .transport
            .invoke("kernel.v1.asset.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn asset_list(&self, params: EmptyParams) -> Result<AssetListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.asset.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn asset_put(&self, params: AssetPutRequest) -> Result<AssetRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.asset.put", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn audit_package(
        &self,
        params: AuditPackageParams,
    ) -> Result<PackageAuditReport> {
        let raw = self
            .transport
            .invoke("kernel.v1.audit.package", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn cap_attenuate(
        &self,
        params: CapAttenuateParams,
    ) -> Result<CapHandleResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.cap.attenuate", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn cap_list_for(
        &self,
        params: CapListForParams,
    ) -> Result<CapHandlesResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.cap.list_for", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn cap_revoke(&self, params: CapRevokeParams) -> Result<CapRevokeResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.cap.revoke", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_cancel(
        &self,
        params: CapabilityCancelParams,
    ) -> Result<StreamFrameEnvelope> {
        let raw = self
            .transport
            .invoke("kernel.v1.capability.cancel", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_describe(
        &self,
        params: EmptyParams,
    ) -> Result<CapabilityDescribeResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.capability.describe", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_discover(
        &self,
        params: EmptyParams,
    ) -> Result<CapabilityDiscoverResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.capability.discover", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_invoke(
        &self,
        params: CapabilityInvocationRequest,
    ) -> Result<CapabilityInvocationResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.capability.invoke", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_stream(
        &self,
        params: CapabilityStreamParams,
    ) -> Result<CapabilityStreamResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.capability.stream", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn event_append(
        &self,
        params: AppendEventRequest,
    ) -> Result<EventEnvelope> {
        let raw = self
            .transport
            .invoke("kernel.v1.event.append", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn event_list(&self, params: EventListRequest) -> Result<EventListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.event.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn event_subscribe(
        &self,
        params: EmptyParams,
    ) -> Result<EventSubscribeResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.event.subscribe", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn extension_point_describe(
        &self,
        params: EmptyParams,
    ) -> Result<ExtensionPointDescribeResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.extension_point.describe", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn extension_point_list(
        &self,
        params: EmptyParams,
    ) -> Result<ExtensionPointListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.extension_point.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn hook_list(&self, params: EmptyParams) -> Result<HookListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.hook.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_diagnostics(
        &self,
        params: EmptyParams,
    ) -> Result<HostDiagnosticsResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.host.diagnostics", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_info(&self, params: EmptyParams) -> Result<HostInfo> {
        let raw = self
            .transport
            .invoke("kernel.v1.host.info", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_ping(&self, params: EmptyParams) -> Result<HostPingResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.host.ping", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_principal(
        &self,
        params: EmptyParams,
    ) -> Result<HostPrincipalResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.host.principal", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn outbound_audit(
        &self,
        params: OutboundAuditParams,
    ) -> Result<OutboundAuditResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.outbound.audit", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn outbound_execute(
        &self,
        params: OutboundExecuteParams,
    ) -> Result<OutboundExecutorResponse> {
        let raw = self
            .transport
            .invoke("kernel.v1.outbound.execute", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn outbound_stream(
        &self,
        params: OutboundStreamParams,
    ) -> Result<KernelOutboundStreamResponse> {
        let raw = self
            .transport
            .invoke("kernel.v1.outbound.stream", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn outbound_websocket_close(
        &self,
        params: OutboundWebSocketSendParams,
    ) -> Result<OutboundWebsocketCloseResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.outbound.websocket.close", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn outbound_websocket_open(
        &self,
        params: OutboundWebSocketOpenRequest,
    ) -> Result<OutboundWebsocketOpenResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.outbound.websocket.open", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn outbound_websocket_send(
        &self,
        params: OutboundWebSocketSendParams,
    ) -> Result<OutboundWebsocketSendResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.outbound.websocket.send", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn package_describe(
        &self,
        params: EmptyParams,
    ) -> Result<PackageDescribeResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.package.describe", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn package_list(&self, params: EmptyParams) -> Result<PackageListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.package.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn package_load(&self, params: PackageManifest) -> Result<PackageRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.package.load", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn package_logs(
        &self,
        params: PackageIdParams,
    ) -> Result<PackageLogsResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.package.logs", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn package_restart(
        &self,
        params: PackageIdParams,
    ) -> Result<PackageRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.package.restart", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn package_status(
        &self,
        params: PackageIdParams,
    ) -> Result<PackageRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.package.status", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn package_unload(
        &self,
        params: PackageIdParams,
    ) -> Result<PackageRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.package.unload", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn permission_audit(
        &self,
        params: EmptyParams,
    ) -> Result<PermissionAuditResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.permission.audit", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn permission_grant(
        &self,
        params: PermissionGrantParams,
    ) -> Result<PermissionGrantRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.permission.grant", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn permission_list(
        &self,
        params: PermissionListParams,
    ) -> Result<PermissionListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.permission.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn permission_revoke(
        &self,
        params: PermissionRevokeParams,
    ) -> Result<PermissionGrantRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.permission.revoke", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn project_get(
        &self,
        params: ProjectIdParams,
    ) -> Result<ProjectGetResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.project.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn project_list(
        &self,
        params: ProjectListParams,
    ) -> Result<ProjectListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.project.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn project_start(
        &self,
        params: ProjectIdParams,
    ) -> Result<ProjectTransitionResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.project.start", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn project_status(
        &self,
        params: ProjectIdParams,
    ) -> Result<ProjectStatusResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.project.status", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn project_stop(
        &self,
        params: ProjectIdParams,
    ) -> Result<ProjectTransitionResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.project.stop", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn projection_get(
        &self,
        params: ProjectionIdParams,
    ) -> Result<ProjectionDefinition> {
        let raw = self
            .transport
            .invoke("kernel.v1.projection.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn projection_list(
        &self,
        params: EmptyParams,
    ) -> Result<ProjectionListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.projection.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn projection_rebuild(
        &self,
        params: ProjectionIdParams,
    ) -> Result<ProjectionDefinition> {
        let raw = self
            .transport
            .invoke("kernel.v1.projection.rebuild", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn projection_register(
        &self,
        params: ProjectionDefinition,
    ) -> Result<ProjectionDefinition> {
        let raw = self
            .transport
            .invoke("kernel.v1.projection.register", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn proposal_apply(
        &self,
        params: ProposalIdParams,
    ) -> Result<ProposalRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.proposal.apply", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn proposal_approve(
        &self,
        params: ProposalDecisionParams,
    ) -> Result<ProposalRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.proposal.approve", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn proposal_create(
        &self,
        params: ProposalRecord,
    ) -> Result<ProposalRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.proposal.create", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn proposal_get(
        &self,
        params: ProposalIdParams,
    ) -> Result<ProposalRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.proposal.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn proposal_list(
        &self,
        params: EmptyParams,
    ) -> Result<ProposalListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.proposal.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn proposal_reject(
        &self,
        params: ProposalDecisionParams,
    ) -> Result<ProposalRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.proposal.reject", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn session_branch_list(
        &self,
        params: SessionBranchListParams,
    ) -> Result<SessionBranchListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.session.branch.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn session_close(
        &self,
        params: SessionCloseParams,
    ) -> Result<EventEnvelope> {
        let raw = self
            .transport
            .invoke("kernel.v1.session.close", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn session_fork(&self, params: SessionForkParams) -> Result<BranchRecord> {
        let raw = self
            .transport
            .invoke("kernel.v1.session.fork", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn session_get(&self, params: EmptyParams) -> Result<SessionGetResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.session.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn session_list(&self, params: EmptyParams) -> Result<SessionListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.session.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn session_open(
        &self,
        params: OpenSessionRequest,
    ) -> Result<KernelSession> {
        let raw = self
            .transport
            .invoke("kernel.v1.session.open", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn surface_contribution_describe(
        &self,
        params: SurfaceDescribeParams,
    ) -> Result<SurfaceContributionDescribeResult> {
        let raw = self
            .transport
            .invoke(
                "kernel.v1.surface.contribution.describe",
                serde_json::to_value(params)?,
            )
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn surface_contribution_list(
        &self,
        params: SurfaceListParams,
    ) -> Result<SurfaceContributionListResult> {
        let raw = self
            .transport
            .invoke("kernel.v1.surface.contribution.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
}
