// @generated by cargo run -p ygg-cli --bin generate-sdks
// TypeScript event payloads generated from docs/spec/v1/schemas/events/.
import type { AssetRecord, BranchRecord, CapabilityFailedPayload, CapabilityInvocationResult, CapabilityInvokedPayload, ErrorShape, OutboundAuditRecord, OutboundExecuteCompletedPayload, OutboundStreamSummary, OutboundWebsocketCompletedPayload, OutboundWebsocketErrorPayload, OutboundWebsocketFramePayload, OutboundWebsocketOpenedPayload, PackageLifecyclePayload, PermissionDeniedPayload, PermissionGrantRecord, ProjectLifecyclePayloadSchema, ProjectionDefinition, ProposalRecord, SessionClosedPayload, SessionOpenedPayload, StreamFrameEnvelope2, StreamFrameEnvelope3, StreamFrameEnvelope4, StreamFrameEnvelope5, StreamFrameEnvelope6, StreamFrameEnvelope7, StreamStartedPayload, SubprocessLogLine } from "./types";

export interface AssetPutEvent {
  kind: "kernel/v1/asset.put";
  payload: AssetRecord;
}

export interface CapabilityCompletedEvent {
  kind: "kernel/v1/capability.completed";
  payload: CapabilityInvocationResult;
}

export interface CapabilityFailedEvent {
  kind: "kernel/v1/capability.failed";
  payload: CapabilityFailedPayload;
}

export interface CapabilityInvokedEvent {
  kind: "kernel/v1/capability.invoked";
  payload: CapabilityInvokedPayload;
}

export interface ErrorEvent {
  kind: "kernel/v1/error";
  payload: ErrorShape;
}

export interface OutboundDeniedEvent {
  kind: "kernel/v1/outbound.denied";
  payload: OutboundAuditRecord;
}

export interface OutboundExecuteCompletedEvent {
  kind: "kernel/v1/outbound.execute.completed";
  payload: OutboundExecuteCompletedPayload;
}

export interface OutboundRequestEvent {
  kind: "kernel/v1/outbound.request";
  payload: OutboundAuditRecord;
}

export interface OutboundStreamCompletedEvent {
  kind: "kernel/v1/outbound.stream.completed";
  payload: OutboundStreamSummary;
}

export interface OutboundWebsocketCompletedEvent {
  kind: "kernel/v1/outbound.websocket.completed";
  payload: OutboundWebsocketCompletedPayload;
}

export interface OutboundWebsocketErrorEvent {
  kind: "kernel/v1/outbound.websocket.error";
  payload: OutboundWebsocketErrorPayload;
}

export interface OutboundWebsocketFrameEvent {
  kind: "kernel/v1/outbound.websocket.frame";
  payload: OutboundWebsocketFramePayload;
}

export interface OutboundWebsocketOpenedEvent {
  kind: "kernel/v1/outbound.websocket.opened";
  payload: OutboundWebsocketOpenedPayload;
}

export interface PackageDegradedEvent {
  kind: "kernel/v1/package.degraded";
  payload: PackageLifecyclePayload;
}

export interface PackageLoadedEvent {
  kind: "kernel/v1/package.loaded";
  payload: PackageLifecyclePayload;
}

export interface PackageLoadingEvent {
  kind: "kernel/v1/package.loading";
  payload: PackageLifecyclePayload;
}

export interface PackageLogEvent {
  kind: "kernel/v1/package.log";
  payload: SubprocessLogLine;
}

export interface PackageReadyEvent {
  kind: "kernel/v1/package.ready";
  payload: PackageLifecyclePayload;
}

export interface PackageStartingEvent {
  kind: "kernel/v1/package.starting";
  payload: PackageLifecyclePayload;
}

export interface PackageStoppedEvent {
  kind: "kernel/v1/package.stopped";
  payload: PackageLifecyclePayload;
}

export interface PackageStoppingEvent {
  kind: "kernel/v1/package.stopping";
  payload: PackageLifecyclePayload;
}

export interface PackageUnloadedEvent {
  kind: "kernel/v1/package.unloaded";
  payload: PackageLifecyclePayload;
}

export interface PermissionDeniedEvent {
  kind: "kernel/v1/permission.denied";
  payload: PermissionDeniedPayload;
}

export interface PermissionGrantedEvent {
  kind: "kernel/v1/permission.granted";
  payload: PermissionGrantRecord;
}

export interface PermissionRevokedEvent {
  kind: "kernel/v1/permission.revoked";
  payload: PermissionGrantRecord;
}

export interface ProjectInstalledEvent {
  kind: "kernel/v1/project.installed";
  payload: ProjectLifecyclePayloadSchema;
}

export interface ProjectStartedEvent {
  kind: "kernel/v1/project.started";
  payload: ProjectLifecyclePayloadSchema;
}

export interface ProjectStoppedEvent {
  kind: "kernel/v1/project.stopped";
  payload: ProjectLifecyclePayloadSchema;
}

export interface ProjectUninstalledEvent {
  kind: "kernel/v1/project.uninstalled";
  payload: ProjectLifecyclePayloadSchema;
}

export interface ProjectionUpdatedEvent {
  kind: "kernel/v1/projection.updated";
  payload: ProjectionDefinition;
}

export interface ProposalAppliedEvent {
  kind: "kernel/v1/proposal.applied";
  payload: ProposalRecord;
}

export interface ProposalApprovedEvent {
  kind: "kernel/v1/proposal.approved";
  payload: ProposalRecord;
}

export interface ProposalCreatedEvent {
  kind: "kernel/v1/proposal.created";
  payload: ProposalRecord;
}

export interface ProposalFailedEvent {
  kind: "kernel/v1/proposal.failed";
  payload: ProposalRecord;
}

export interface ProposalRejectedEvent {
  kind: "kernel/v1/proposal.rejected";
  payload: ProposalRecord;
}

export interface SessionClosedEvent {
  kind: "kernel/v1/session.closed";
  payload: SessionClosedPayload;
}

export interface SessionForkedEvent {
  kind: "kernel/v1/session.forked";
  payload: BranchRecord;
}

export interface SessionOpenedEvent {
  kind: "kernel/v1/session.opened";
  payload: SessionOpenedPayload;
}

export interface StreamCancelledEvent {
  kind: "kernel/v1/stream.cancelled";
  payload: StreamFrameEnvelope2;
}

export interface StreamChunkEvent {
  kind: "kernel/v1/stream.chunk";
  payload: StreamFrameEnvelope3;
}

export interface StreamEndedEvent {
  kind: "kernel/v1/stream.ended";
  payload: StreamFrameEnvelope4;
}

export interface StreamErrorEvent {
  kind: "kernel/v1/stream.error";
  payload: StreamFrameEnvelope5;
}

export interface StreamProgressEvent {
  kind: "kernel/v1/stream.progress";
  payload: StreamFrameEnvelope6;
}

export interface StreamStartedEvent {
  kind: "kernel/v1/stream.started";
  payload: StreamStartedPayload;
}

export interface StreamTimeoutEvent {
  kind: "kernel/v1/stream.timeout";
  payload: StreamFrameEnvelope7;
}

export interface KernelEventPayloadMap {
  "kernel/v1/asset.put": AssetRecord;
  "kernel/v1/capability.completed": CapabilityInvocationResult;
  "kernel/v1/capability.failed": CapabilityFailedPayload;
  "kernel/v1/capability.invoked": CapabilityInvokedPayload;
  "kernel/v1/error": ErrorShape;
  "kernel/v1/outbound.denied": OutboundAuditRecord;
  "kernel/v1/outbound.execute.completed": OutboundExecuteCompletedPayload;
  "kernel/v1/outbound.request": OutboundAuditRecord;
  "kernel/v1/outbound.stream.completed": OutboundStreamSummary;
  "kernel/v1/outbound.websocket.completed": OutboundWebsocketCompletedPayload;
  "kernel/v1/outbound.websocket.error": OutboundWebsocketErrorPayload;
  "kernel/v1/outbound.websocket.frame": OutboundWebsocketFramePayload;
  "kernel/v1/outbound.websocket.opened": OutboundWebsocketOpenedPayload;
  "kernel/v1/package.degraded": PackageLifecyclePayload;
  "kernel/v1/package.loaded": PackageLifecyclePayload;
  "kernel/v1/package.loading": PackageLifecyclePayload;
  "kernel/v1/package.log": SubprocessLogLine;
  "kernel/v1/package.ready": PackageLifecyclePayload;
  "kernel/v1/package.starting": PackageLifecyclePayload;
  "kernel/v1/package.stopped": PackageLifecyclePayload;
  "kernel/v1/package.stopping": PackageLifecyclePayload;
  "kernel/v1/package.unloaded": PackageLifecyclePayload;
  "kernel/v1/permission.denied": PermissionDeniedPayload;
  "kernel/v1/permission.granted": PermissionGrantRecord;
  "kernel/v1/permission.revoked": PermissionGrantRecord;
  "kernel/v1/project.installed": ProjectLifecyclePayloadSchema;
  "kernel/v1/project.started": ProjectLifecyclePayloadSchema;
  "kernel/v1/project.stopped": ProjectLifecyclePayloadSchema;
  "kernel/v1/project.uninstalled": ProjectLifecyclePayloadSchema;
  "kernel/v1/projection.updated": ProjectionDefinition;
  "kernel/v1/proposal.applied": ProposalRecord;
  "kernel/v1/proposal.approved": ProposalRecord;
  "kernel/v1/proposal.created": ProposalRecord;
  "kernel/v1/proposal.failed": ProposalRecord;
  "kernel/v1/proposal.rejected": ProposalRecord;
  "kernel/v1/session.closed": SessionClosedPayload;
  "kernel/v1/session.forked": BranchRecord;
  "kernel/v1/session.opened": SessionOpenedPayload;
  "kernel/v1/stream.cancelled": StreamFrameEnvelope2;
  "kernel/v1/stream.chunk": StreamFrameEnvelope3;
  "kernel/v1/stream.ended": StreamFrameEnvelope4;
  "kernel/v1/stream.error": StreamFrameEnvelope5;
  "kernel/v1/stream.progress": StreamFrameEnvelope6;
  "kernel/v1/stream.started": StreamStartedPayload;
  "kernel/v1/stream.timeout": StreamFrameEnvelope7;
}

export type KernelEvent =
  | AssetPutEvent
  | CapabilityCompletedEvent
  | CapabilityFailedEvent
  | CapabilityInvokedEvent
  | ErrorEvent
  | OutboundDeniedEvent
  | OutboundExecuteCompletedEvent
  | OutboundRequestEvent
  | OutboundStreamCompletedEvent
  | OutboundWebsocketCompletedEvent
  | OutboundWebsocketErrorEvent
  | OutboundWebsocketFrameEvent
  | OutboundWebsocketOpenedEvent
  | PackageDegradedEvent
  | PackageLoadedEvent
  | PackageLoadingEvent
  | PackageLogEvent
  | PackageReadyEvent
  | PackageStartingEvent
  | PackageStoppedEvent
  | PackageStoppingEvent
  | PackageUnloadedEvent
  | PermissionDeniedEvent
  | PermissionGrantedEvent
  | PermissionRevokedEvent
  | ProjectInstalledEvent
  | ProjectStartedEvent
  | ProjectStoppedEvent
  | ProjectUninstalledEvent
  | ProjectionUpdatedEvent
  | ProposalAppliedEvent
  | ProposalApprovedEvent
  | ProposalCreatedEvent
  | ProposalFailedEvent
  | ProposalRejectedEvent
  | SessionClosedEvent
  | SessionForkedEvent
  | SessionOpenedEvent
  | StreamCancelledEvent
  | StreamChunkEvent
  | StreamEndedEvent
  | StreamErrorEvent
  | StreamProgressEvent
  | StreamStartedEvent
  | StreamTimeoutEvent
;
