// @generated by cargo run -p ygg-cli --bin generate-sdks
// TypeScript client methods generated from docs/spec/v1/schemas/methods/.
import type { KernelClient } from "./client";
import type { AppendEventRequest, AssetGetParams, AssetGetResponse, AssetListResult, AssetPutRequest, AssetRecord, AuditPackageParams, BranchRecord, CapAttenuateParams, CapHandleResult, CapHandlesResult, CapListForParams, CapRevokeParams, CapRevokeResult, CapabilityCancelParams, CapabilityDescribeResult, CapabilityDiscoverResult, CapabilityInvocationRequest, CapabilityInvocationResult, CapabilityStreamParams, CapabilityStreamResult, EmptyParams, EventEnvelope, EventListRequest, EventListResult, EventSubscribeResult, ExtensionPointDescribeResult, ExtensionPointListResult, HookListResult, HostDiagnosticsResult, HostInfo, HostPingResult, HostPrincipalResult, KernelOutboundStreamResponse, KernelSession, OpenSessionRequest, OutboundAuditParams, OutboundAuditResult, OutboundExecuteParams, OutboundExecutorResponse, OutboundStreamParams, OutboundWebSocketOpenRequest, OutboundWebSocketSendParams, OutboundWebsocketCloseResult, OutboundWebsocketOpenResult, OutboundWebsocketSendResult, PackageAuditReport, PackageDescribeResult, PackageIdParams, PackageListResult, PackageLogsResult, PackageManifest, PackageRecord, PermissionAuditResult, PermissionGrantParams, PermissionGrantRecord, PermissionListParams, PermissionListResult, PermissionRevokeParams, ProjectGetResult, ProjectIdParams, ProjectListParams, ProjectListResultSchema, ProjectStartResult, ProjectStatusResult, ProjectStopResult, ProjectionDefinition, ProjectionIdParams, ProjectionListResult, ProposalDecisionParams, ProposalIdParams, ProposalListResult, ProposalRecord, SessionBranchListParams, SessionBranchListResult, SessionCloseParams, SessionForkParams, SessionGetParams, SessionListResult, StreamFrameEnvelope, SurfaceContributionDescribeResult, SurfaceContributionListResult, SurfaceDescribeParams, SurfaceListParams, SurfaceResolveBundleParams, SurfaceResolveBundleResult } from "./types";

export interface KernelMethods {
  assetGet(params: AssetGetParams): Promise<AssetGetResponse>;
  assetList(params: EmptyParams): Promise<AssetListResult>;
  assetPut(params: AssetPutRequest): Promise<AssetRecord>;
  auditPackage(params: AuditPackageParams): Promise<PackageAuditReport>;
  capAttenuate(params: CapAttenuateParams): Promise<CapHandleResult>;
  capListFor(params: CapListForParams): Promise<CapHandlesResult>;
  capRevoke(params: CapRevokeParams): Promise<CapRevokeResult>;
  capabilityCancel(params: CapabilityCancelParams): Promise<StreamFrameEnvelope>;
  capabilityDescribe(params: EmptyParams): Promise<CapabilityDescribeResult>;
  capabilityDiscover(params: EmptyParams): Promise<CapabilityDiscoverResult>;
  capabilityInvoke(params: CapabilityInvocationRequest): Promise<CapabilityInvocationResult>;
  capabilityStream(params: CapabilityStreamParams): Promise<CapabilityStreamResult>;
  eventAppend(params: AppendEventRequest): Promise<EventEnvelope>;
  eventList(params: EventListRequest): Promise<EventListResult>;
  eventSubscribe(params: EmptyParams): Promise<EventSubscribeResult>;
  extensionPointDescribe(params: EmptyParams): Promise<ExtensionPointDescribeResult>;
  extensionPointList(params: EmptyParams): Promise<ExtensionPointListResult>;
  hookList(params: EmptyParams): Promise<HookListResult>;
  hostDiagnostics(params: EmptyParams): Promise<HostDiagnosticsResult>;
  hostInfo(params: EmptyParams): Promise<HostInfo>;
  hostPing(params: EmptyParams): Promise<HostPingResult>;
  hostPrincipal(params: EmptyParams): Promise<HostPrincipalResult>;
  outboundAudit(params: OutboundAuditParams): Promise<OutboundAuditResult>;
  outboundExecute(params: OutboundExecuteParams): Promise<OutboundExecutorResponse>;
  outboundStream(params: OutboundStreamParams): Promise<KernelOutboundStreamResponse>;
  outboundWebsocketClose(params: OutboundWebSocketSendParams): Promise<OutboundWebsocketCloseResult>;
  outboundWebsocketOpen(params: OutboundWebSocketOpenRequest): Promise<OutboundWebsocketOpenResult>;
  outboundWebsocketSend(params: OutboundWebSocketSendParams): Promise<OutboundWebsocketSendResult>;
  packageDescribe(params: EmptyParams): Promise<PackageDescribeResult>;
  packageList(params: EmptyParams): Promise<PackageListResult>;
  packageLoad(params: PackageManifest): Promise<PackageRecord>;
  packageLogs(params: PackageIdParams): Promise<PackageLogsResult>;
  packageRestart(params: PackageIdParams): Promise<PackageRecord>;
  packageStatus(params: PackageIdParams): Promise<PackageRecord>;
  packageUnload(params: PackageIdParams): Promise<PackageRecord>;
  permissionAudit(params: EmptyParams): Promise<PermissionAuditResult>;
  permissionGrant(params: PermissionGrantParams): Promise<PermissionGrantRecord>;
  permissionList(params: PermissionListParams): Promise<PermissionListResult>;
  permissionRevoke(params: PermissionRevokeParams): Promise<PermissionGrantRecord>;
  projectGet(params: ProjectIdParams): Promise<ProjectGetResult>;
  projectList(params: ProjectListParams): Promise<ProjectListResultSchema>;
  projectStart(params: ProjectIdParams): Promise<ProjectStartResult>;
  projectStatus(params: ProjectIdParams): Promise<ProjectStatusResult>;
  projectStop(params: ProjectIdParams): Promise<ProjectStopResult>;
  projectionGet(params: ProjectionIdParams): Promise<ProjectionDefinition>;
  projectionList(params: EmptyParams): Promise<ProjectionListResult>;
  projectionRebuild(params: ProjectionIdParams): Promise<ProjectionDefinition>;
  projectionRegister(params: ProjectionDefinition): Promise<ProjectionDefinition>;
  proposalApply(params: ProposalIdParams): Promise<ProposalRecord>;
  proposalApprove(params: ProposalDecisionParams): Promise<ProposalRecord>;
  proposalCreate(params: ProposalRecord): Promise<ProposalRecord>;
  proposalGet(params: ProposalIdParams): Promise<ProposalRecord>;
  proposalList(params: EmptyParams): Promise<ProposalListResult>;
  proposalReject(params: ProposalDecisionParams): Promise<ProposalRecord>;
  sessionBranchList(params: SessionBranchListParams): Promise<SessionBranchListResult>;
  sessionClose(params: SessionCloseParams): Promise<EventEnvelope>;
  sessionFork(params: SessionForkParams): Promise<BranchRecord>;
  sessionGet(params: SessionGetParams): Promise<KernelSession>;
  sessionList(params: EmptyParams): Promise<SessionListResult>;
  sessionOpen(params: OpenSessionRequest): Promise<KernelSession>;
  surfaceContributionDescribe(params: SurfaceDescribeParams): Promise<SurfaceContributionDescribeResult>;
  surfaceContributionList(params: SurfaceListParams): Promise<SurfaceContributionListResult>;
  surfaceResolveBundle(params: SurfaceResolveBundleParams): Promise<SurfaceResolveBundleResult>;
}

declare module "./client" {
  interface KernelClient extends KernelMethods {}
}

export async function assetGet(
  this: KernelClient,
  params: AssetGetParams,
): Promise<AssetGetResponse> {
  return this.transport.invoke("kernel.v1.asset.get", params) as Promise<AssetGetResponse>;
}

export async function assetList(
  this: KernelClient,
  params: EmptyParams,
): Promise<AssetListResult> {
  return this.transport.invoke("kernel.v1.asset.list", params) as Promise<AssetListResult>;
}

export async function assetPut(
  this: KernelClient,
  params: AssetPutRequest,
): Promise<AssetRecord> {
  return this.transport.invoke("kernel.v1.asset.put", params) as Promise<AssetRecord>;
}

export async function auditPackage(
  this: KernelClient,
  params: AuditPackageParams,
): Promise<PackageAuditReport> {
  return this.transport.invoke("kernel.v1.audit.package", params) as Promise<PackageAuditReport>;
}

export async function capAttenuate(
  this: KernelClient,
  params: CapAttenuateParams,
): Promise<CapHandleResult> {
  return this.transport.invoke("kernel.v1.cap.attenuate", params) as Promise<CapHandleResult>;
}

export async function capListFor(
  this: KernelClient,
  params: CapListForParams,
): Promise<CapHandlesResult> {
  return this.transport.invoke("kernel.v1.cap.list_for", params) as Promise<CapHandlesResult>;
}

export async function capRevoke(
  this: KernelClient,
  params: CapRevokeParams,
): Promise<CapRevokeResult> {
  return this.transport.invoke("kernel.v1.cap.revoke", params) as Promise<CapRevokeResult>;
}

export async function capabilityCancel(
  this: KernelClient,
  params: CapabilityCancelParams,
): Promise<StreamFrameEnvelope> {
  return this.transport.invoke("kernel.v1.capability.cancel", params) as Promise<StreamFrameEnvelope>;
}

export async function capabilityDescribe(
  this: KernelClient,
  params: EmptyParams,
): Promise<CapabilityDescribeResult> {
  return this.transport.invoke("kernel.v1.capability.describe", params) as Promise<CapabilityDescribeResult>;
}

export async function capabilityDiscover(
  this: KernelClient,
  params: EmptyParams,
): Promise<CapabilityDiscoverResult> {
  return this.transport.invoke("kernel.v1.capability.discover", params) as Promise<CapabilityDiscoverResult>;
}

export async function capabilityInvoke(
  this: KernelClient,
  params: CapabilityInvocationRequest,
): Promise<CapabilityInvocationResult> {
  return this.transport.invoke("kernel.v1.capability.invoke", params) as Promise<CapabilityInvocationResult>;
}

export async function capabilityStream(
  this: KernelClient,
  params: CapabilityStreamParams,
): Promise<CapabilityStreamResult> {
  return this.transport.invoke("kernel.v1.capability.stream", params) as Promise<CapabilityStreamResult>;
}

export async function eventAppend(
  this: KernelClient,
  params: AppendEventRequest,
): Promise<EventEnvelope> {
  return this.transport.invoke("kernel.v1.event.append", params) as Promise<EventEnvelope>;
}

export async function eventList(
  this: KernelClient,
  params: EventListRequest,
): Promise<EventListResult> {
  return this.transport.invoke("kernel.v1.event.list", params) as Promise<EventListResult>;
}

export async function eventSubscribe(
  this: KernelClient,
  params: EmptyParams,
): Promise<EventSubscribeResult> {
  return this.transport.invoke("kernel.v1.event.subscribe", params) as Promise<EventSubscribeResult>;
}

export async function extensionPointDescribe(
  this: KernelClient,
  params: EmptyParams,
): Promise<ExtensionPointDescribeResult> {
  return this.transport.invoke("kernel.v1.extension_point.describe", params) as Promise<ExtensionPointDescribeResult>;
}

export async function extensionPointList(
  this: KernelClient,
  params: EmptyParams,
): Promise<ExtensionPointListResult> {
  return this.transport.invoke("kernel.v1.extension_point.list", params) as Promise<ExtensionPointListResult>;
}

export async function hookList(
  this: KernelClient,
  params: EmptyParams,
): Promise<HookListResult> {
  return this.transport.invoke("kernel.v1.hook.list", params) as Promise<HookListResult>;
}

export async function hostDiagnostics(
  this: KernelClient,
  params: EmptyParams,
): Promise<HostDiagnosticsResult> {
  return this.transport.invoke("kernel.v1.host.diagnostics", params) as Promise<HostDiagnosticsResult>;
}

export async function hostInfo(
  this: KernelClient,
  params: EmptyParams,
): Promise<HostInfo> {
  return this.transport.invoke("kernel.v1.host.info", params) as Promise<HostInfo>;
}

export async function hostPing(
  this: KernelClient,
  params: EmptyParams,
): Promise<HostPingResult> {
  return this.transport.invoke("kernel.v1.host.ping", params) as Promise<HostPingResult>;
}

export async function hostPrincipal(
  this: KernelClient,
  params: EmptyParams,
): Promise<HostPrincipalResult> {
  return this.transport.invoke("kernel.v1.host.principal", params) as Promise<HostPrincipalResult>;
}

export async function outboundAudit(
  this: KernelClient,
  params: OutboundAuditParams,
): Promise<OutboundAuditResult> {
  return this.transport.invoke("kernel.v1.outbound.audit", params) as Promise<OutboundAuditResult>;
}

export async function outboundExecute(
  this: KernelClient,
  params: OutboundExecuteParams,
): Promise<OutboundExecutorResponse> {
  return this.transport.invoke("kernel.v1.outbound.execute", params) as Promise<OutboundExecutorResponse>;
}

export async function outboundStream(
  this: KernelClient,
  params: OutboundStreamParams,
): Promise<KernelOutboundStreamResponse> {
  return this.transport.invoke("kernel.v1.outbound.stream", params) as Promise<KernelOutboundStreamResponse>;
}

export async function outboundWebsocketClose(
  this: KernelClient,
  params: OutboundWebSocketSendParams,
): Promise<OutboundWebsocketCloseResult> {
  return this.transport.invoke("kernel.v1.outbound.websocket.close", params) as Promise<OutboundWebsocketCloseResult>;
}

export async function outboundWebsocketOpen(
  this: KernelClient,
  params: OutboundWebSocketOpenRequest,
): Promise<OutboundWebsocketOpenResult> {
  return this.transport.invoke("kernel.v1.outbound.websocket.open", params) as Promise<OutboundWebsocketOpenResult>;
}

export async function outboundWebsocketSend(
  this: KernelClient,
  params: OutboundWebSocketSendParams,
): Promise<OutboundWebsocketSendResult> {
  return this.transport.invoke("kernel.v1.outbound.websocket.send", params) as Promise<OutboundWebsocketSendResult>;
}

export async function packageDescribe(
  this: KernelClient,
  params: EmptyParams,
): Promise<PackageDescribeResult> {
  return this.transport.invoke("kernel.v1.package.describe", params) as Promise<PackageDescribeResult>;
}

export async function packageList(
  this: KernelClient,
  params: EmptyParams,
): Promise<PackageListResult> {
  return this.transport.invoke("kernel.v1.package.list", params) as Promise<PackageListResult>;
}

export async function packageLoad(
  this: KernelClient,
  params: PackageManifest,
): Promise<PackageRecord> {
  return this.transport.invoke("kernel.v1.package.load", params) as Promise<PackageRecord>;
}

export async function packageLogs(
  this: KernelClient,
  params: PackageIdParams,
): Promise<PackageLogsResult> {
  return this.transport.invoke("kernel.v1.package.logs", params) as Promise<PackageLogsResult>;
}

export async function packageRestart(
  this: KernelClient,
  params: PackageIdParams,
): Promise<PackageRecord> {
  return this.transport.invoke("kernel.v1.package.restart", params) as Promise<PackageRecord>;
}

export async function packageStatus(
  this: KernelClient,
  params: PackageIdParams,
): Promise<PackageRecord> {
  return this.transport.invoke("kernel.v1.package.status", params) as Promise<PackageRecord>;
}

export async function packageUnload(
  this: KernelClient,
  params: PackageIdParams,
): Promise<PackageRecord> {
  return this.transport.invoke("kernel.v1.package.unload", params) as Promise<PackageRecord>;
}

export async function permissionAudit(
  this: KernelClient,
  params: EmptyParams,
): Promise<PermissionAuditResult> {
  return this.transport.invoke("kernel.v1.permission.audit", params) as Promise<PermissionAuditResult>;
}

export async function permissionGrant(
  this: KernelClient,
  params: PermissionGrantParams,
): Promise<PermissionGrantRecord> {
  return this.transport.invoke("kernel.v1.permission.grant", params) as Promise<PermissionGrantRecord>;
}

export async function permissionList(
  this: KernelClient,
  params: PermissionListParams,
): Promise<PermissionListResult> {
  return this.transport.invoke("kernel.v1.permission.list", params) as Promise<PermissionListResult>;
}

export async function permissionRevoke(
  this: KernelClient,
  params: PermissionRevokeParams,
): Promise<PermissionGrantRecord> {
  return this.transport.invoke("kernel.v1.permission.revoke", params) as Promise<PermissionGrantRecord>;
}

export async function projectGet(
  this: KernelClient,
  params: ProjectIdParams,
): Promise<ProjectGetResult> {
  return this.transport.invoke("kernel.v1.project.get", params) as Promise<ProjectGetResult>;
}

export async function projectList(
  this: KernelClient,
  params: ProjectListParams,
): Promise<ProjectListResultSchema> {
  return this.transport.invoke("kernel.v1.project.list", params) as Promise<ProjectListResultSchema>;
}

export async function projectStart(
  this: KernelClient,
  params: ProjectIdParams,
): Promise<ProjectStartResult> {
  return this.transport.invoke("kernel.v1.project.start", params) as Promise<ProjectStartResult>;
}

export async function projectStatus(
  this: KernelClient,
  params: ProjectIdParams,
): Promise<ProjectStatusResult> {
  return this.transport.invoke("kernel.v1.project.status", params) as Promise<ProjectStatusResult>;
}

export async function projectStop(
  this: KernelClient,
  params: ProjectIdParams,
): Promise<ProjectStopResult> {
  return this.transport.invoke("kernel.v1.project.stop", params) as Promise<ProjectStopResult>;
}

export async function projectionGet(
  this: KernelClient,
  params: ProjectionIdParams,
): Promise<ProjectionDefinition> {
  return this.transport.invoke("kernel.v1.projection.get", params) as Promise<ProjectionDefinition>;
}

export async function projectionList(
  this: KernelClient,
  params: EmptyParams,
): Promise<ProjectionListResult> {
  return this.transport.invoke("kernel.v1.projection.list", params) as Promise<ProjectionListResult>;
}

export async function projectionRebuild(
  this: KernelClient,
  params: ProjectionIdParams,
): Promise<ProjectionDefinition> {
  return this.transport.invoke("kernel.v1.projection.rebuild", params) as Promise<ProjectionDefinition>;
}

export async function projectionRegister(
  this: KernelClient,
  params: ProjectionDefinition,
): Promise<ProjectionDefinition> {
  return this.transport.invoke("kernel.v1.projection.register", params) as Promise<ProjectionDefinition>;
}

export async function proposalApply(
  this: KernelClient,
  params: ProposalIdParams,
): Promise<ProposalRecord> {
  return this.transport.invoke("kernel.v1.proposal.apply", params) as Promise<ProposalRecord>;
}

export async function proposalApprove(
  this: KernelClient,
  params: ProposalDecisionParams,
): Promise<ProposalRecord> {
  return this.transport.invoke("kernel.v1.proposal.approve", params) as Promise<ProposalRecord>;
}

export async function proposalCreate(
  this: KernelClient,
  params: ProposalRecord,
): Promise<ProposalRecord> {
  return this.transport.invoke("kernel.v1.proposal.create", params) as Promise<ProposalRecord>;
}

export async function proposalGet(
  this: KernelClient,
  params: ProposalIdParams,
): Promise<ProposalRecord> {
  return this.transport.invoke("kernel.v1.proposal.get", params) as Promise<ProposalRecord>;
}

export async function proposalList(
  this: KernelClient,
  params: EmptyParams,
): Promise<ProposalListResult> {
  return this.transport.invoke("kernel.v1.proposal.list", params) as Promise<ProposalListResult>;
}

export async function proposalReject(
  this: KernelClient,
  params: ProposalDecisionParams,
): Promise<ProposalRecord> {
  return this.transport.invoke("kernel.v1.proposal.reject", params) as Promise<ProposalRecord>;
}

export async function sessionBranchList(
  this: KernelClient,
  params: SessionBranchListParams,
): Promise<SessionBranchListResult> {
  return this.transport.invoke("kernel.v1.session.branch.list", params) as Promise<SessionBranchListResult>;
}

export async function sessionClose(
  this: KernelClient,
  params: SessionCloseParams,
): Promise<EventEnvelope> {
  return this.transport.invoke("kernel.v1.session.close", params) as Promise<EventEnvelope>;
}

export async function sessionFork(
  this: KernelClient,
  params: SessionForkParams,
): Promise<BranchRecord> {
  return this.transport.invoke("kernel.v1.session.fork", params) as Promise<BranchRecord>;
}

export async function sessionGet(
  this: KernelClient,
  params: SessionGetParams,
): Promise<KernelSession> {
  return this.transport.invoke("kernel.v1.session.get", params) as Promise<KernelSession>;
}

export async function sessionList(
  this: KernelClient,
  params: EmptyParams,
): Promise<SessionListResult> {
  return this.transport.invoke("kernel.v1.session.list", params) as Promise<SessionListResult>;
}

export async function sessionOpen(
  this: KernelClient,
  params: OpenSessionRequest,
): Promise<KernelSession> {
  return this.transport.invoke("kernel.v1.session.open", params) as Promise<KernelSession>;
}

export async function surfaceContributionDescribe(
  this: KernelClient,
  params: SurfaceDescribeParams,
): Promise<SurfaceContributionDescribeResult> {
  return this.transport.invoke("kernel.v1.surface.contribution.describe", params) as Promise<SurfaceContributionDescribeResult>;
}

export async function surfaceContributionList(
  this: KernelClient,
  params: SurfaceListParams,
): Promise<SurfaceContributionListResult> {
  return this.transport.invoke("kernel.v1.surface.contribution.list", params) as Promise<SurfaceContributionListResult>;
}

export async function surfaceResolveBundle(
  this: KernelClient,
  params: SurfaceResolveBundleParams,
): Promise<SurfaceResolveBundleResult> {
  return this.transport.invoke("kernel.v1.surface.resolve_bundle", params) as Promise<SurfaceResolveBundleResult>;
}

export function attach<T extends KernelClient>(client: T): T & KernelMethods {
  (client as T & KernelMethods).assetGet = assetGet.bind(client);
  (client as T & KernelMethods).assetList = assetList.bind(client);
  (client as T & KernelMethods).assetPut = assetPut.bind(client);
  (client as T & KernelMethods).auditPackage = auditPackage.bind(client);
  (client as T & KernelMethods).capAttenuate = capAttenuate.bind(client);
  (client as T & KernelMethods).capListFor = capListFor.bind(client);
  (client as T & KernelMethods).capRevoke = capRevoke.bind(client);
  (client as T & KernelMethods).capabilityCancel = capabilityCancel.bind(client);
  (client as T & KernelMethods).capabilityDescribe = capabilityDescribe.bind(client);
  (client as T & KernelMethods).capabilityDiscover = capabilityDiscover.bind(client);
  (client as T & KernelMethods).capabilityInvoke = capabilityInvoke.bind(client);
  (client as T & KernelMethods).capabilityStream = capabilityStream.bind(client);
  (client as T & KernelMethods).eventAppend = eventAppend.bind(client);
  (client as T & KernelMethods).eventList = eventList.bind(client);
  (client as T & KernelMethods).eventSubscribe = eventSubscribe.bind(client);
  (client as T & KernelMethods).extensionPointDescribe = extensionPointDescribe.bind(client);
  (client as T & KernelMethods).extensionPointList = extensionPointList.bind(client);
  (client as T & KernelMethods).hookList = hookList.bind(client);
  (client as T & KernelMethods).hostDiagnostics = hostDiagnostics.bind(client);
  (client as T & KernelMethods).hostInfo = hostInfo.bind(client);
  (client as T & KernelMethods).hostPing = hostPing.bind(client);
  (client as T & KernelMethods).hostPrincipal = hostPrincipal.bind(client);
  (client as T & KernelMethods).outboundAudit = outboundAudit.bind(client);
  (client as T & KernelMethods).outboundExecute = outboundExecute.bind(client);
  (client as T & KernelMethods).outboundStream = outboundStream.bind(client);
  (client as T & KernelMethods).outboundWebsocketClose = outboundWebsocketClose.bind(client);
  (client as T & KernelMethods).outboundWebsocketOpen = outboundWebsocketOpen.bind(client);
  (client as T & KernelMethods).outboundWebsocketSend = outboundWebsocketSend.bind(client);
  (client as T & KernelMethods).packageDescribe = packageDescribe.bind(client);
  (client as T & KernelMethods).packageList = packageList.bind(client);
  (client as T & KernelMethods).packageLoad = packageLoad.bind(client);
  (client as T & KernelMethods).packageLogs = packageLogs.bind(client);
  (client as T & KernelMethods).packageRestart = packageRestart.bind(client);
  (client as T & KernelMethods).packageStatus = packageStatus.bind(client);
  (client as T & KernelMethods).packageUnload = packageUnload.bind(client);
  (client as T & KernelMethods).permissionAudit = permissionAudit.bind(client);
  (client as T & KernelMethods).permissionGrant = permissionGrant.bind(client);
  (client as T & KernelMethods).permissionList = permissionList.bind(client);
  (client as T & KernelMethods).permissionRevoke = permissionRevoke.bind(client);
  (client as T & KernelMethods).projectGet = projectGet.bind(client);
  (client as T & KernelMethods).projectList = projectList.bind(client);
  (client as T & KernelMethods).projectStart = projectStart.bind(client);
  (client as T & KernelMethods).projectStatus = projectStatus.bind(client);
  (client as T & KernelMethods).projectStop = projectStop.bind(client);
  (client as T & KernelMethods).projectionGet = projectionGet.bind(client);
  (client as T & KernelMethods).projectionList = projectionList.bind(client);
  (client as T & KernelMethods).projectionRebuild = projectionRebuild.bind(client);
  (client as T & KernelMethods).projectionRegister = projectionRegister.bind(client);
  (client as T & KernelMethods).proposalApply = proposalApply.bind(client);
  (client as T & KernelMethods).proposalApprove = proposalApprove.bind(client);
  (client as T & KernelMethods).proposalCreate = proposalCreate.bind(client);
  (client as T & KernelMethods).proposalGet = proposalGet.bind(client);
  (client as T & KernelMethods).proposalList = proposalList.bind(client);
  (client as T & KernelMethods).proposalReject = proposalReject.bind(client);
  (client as T & KernelMethods).sessionBranchList = sessionBranchList.bind(client);
  (client as T & KernelMethods).sessionClose = sessionClose.bind(client);
  (client as T & KernelMethods).sessionFork = sessionFork.bind(client);
  (client as T & KernelMethods).sessionGet = sessionGet.bind(client);
  (client as T & KernelMethods).sessionList = sessionList.bind(client);
  (client as T & KernelMethods).sessionOpen = sessionOpen.bind(client);
  (client as T & KernelMethods).surfaceContributionDescribe = surfaceContributionDescribe.bind(client);
  (client as T & KernelMethods).surfaceContributionList = surfaceContributionList.bind(client);
  (client as T & KernelMethods).surfaceResolveBundle = surfaceResolveBundle.bind(client);
  return client as T & KernelMethods;
}
