// @generated by cargo run -p ygg-cli --bin generate-sdks
// TypeScript types generated from docs/spec/v1/schemas/.

export interface AppendEventRequest {
  "kind": string;
  "metadata": unknown;
  "payload": unknown;
  "session_id": string;
  "writer_package_id": string;
}

export interface AssetGetParams {
  "asset_id": string;
}

export interface AssetGetResponse {
  "content": string;
  "record": AssetRecord;
}

export type AssetListResult = Array<{
  "created_at": string;
  "hash": string;
  "id": string;
  "metadata"?: unknown;
  "mime": string;
  "origin_package_id": string;
  "size_bytes": number;
}>;

export interface AssetPermissions {
  "read"?: boolean;
  "write"?: boolean;
}

export interface AssetPutRequest {
  "content": string;
  "metadata"?: unknown;
  "mime": string;
  "origin_package_id"?: null | string;
}

export interface AssetRecord {
  "created_at": string;
  "hash": string;
  "id": string;
  "metadata"?: unknown;
  "mime": string;
  "origin_package_id": string;
  "size_bytes": number;
}

export interface AuditPackageParams {
  "package_id": string;
  "since"?: null | string;
  "until"?: null | string;
}

export interface BranchRecord {
  "child_session_id": string;
  "created_at": string;
  "forked_from_sequence": number;
  "id": string;
  "metadata"?: unknown;
  "parent_session_id": string;
}

export interface CapAttenuateParams {
  "constraints": unknown;
  "parent_handle": CapHandleId;
}

export interface CapHandle {
  "cap_type": string;
  "cap_version": string;
  "constraints": unknown;
  "id": CapHandleId;
  "lease": HandleLease;
  "parent"?: CapHandleId | null;
  "provenance": HandleProvenance;
  "revoked": boolean;
  "scope": HandleScope;
}

export type CapHandleId = string;

export interface CapHandleResult {
  "handle": CapHandle;
}

export interface CapHandlesResult {
  "handles": Array<CapHandle>;
}

export interface CapListForParams {
  "package_id": string;
}

export interface CapRevokeParams {
  "handle": CapHandleId;
}

export type CapRevokeResult = Record<string, unknown>;

export interface CapabilityCancelParams {
  "invocation_id"?: null | string;
  "session_id"?: null | string;
  "stream_id"?: null | string;
}

export type CapabilityDescribeResult = null;

export interface CapabilityDescriptor {
  "description"?: null | string;
  "id": string;
  "input_schema"?: unknown;
  "output_schema"?: unknown;
  "side_effects"?: Array<string>;
  "streaming"?: boolean;
  "version": string;
}

export type CapabilityDiscoverResult = Array<{
  "descriptor": CapabilityDescriptor;
  "provider_package_id": string;
}>;

export type CapabilityFailedPayload = Record<string, unknown>;

export interface CapabilityInvocationRequest {
  "caller_package_id"?: null | string;
  /**
   * Legacy path. Runtime auto-mints a one-use transient handle when no handle is supplied.
   */
  "capability_id"?: null | string;
  /**
   * New preferred path: invoke by kernel-minted handle.
   */
  "handle"?: CapHandleId | null;
  "input"?: unknown;
  "provider_package_id"?: null | string;
  /**
   * Kernel session id this invocation is part of, if any. Propagated from ProtocolContext for downstream scope resolution.
   */
  "session_id"?: null | string;
  "version"?: null | string;
}

export interface CapabilityInvocationResult {
  "capability_id": string;
  "correlation_id": string;
  "duration_ms": number;
  "output": unknown;
  "provider_package_id": string;
}

export type CapabilityInvokedPayload = Record<string, unknown>;

export interface CapabilityPermissions {
  "invoke"?: Array<string>;
}

export interface CapabilityRequirement {
  "id": string;
  "version": string;
}

export interface CapabilityStreamParams {
  "capability_id": string;
  "input": unknown;
  "provider_package_id"?: null | string;
}

export type CapabilityStreamResult = Record<string, unknown>;

export type ContractMode = "none" | "v1";

export interface DeclaredAuthority {
  "assets_read": boolean;
  "assets_write": boolean;
  "capabilities_invoke": Array<string>;
  "events_append": boolean;
  "events_read": boolean;
  "network_hosts": Array<string>;
  "secret_refs": Array<string>;
}

export type DependencySource = {
  "kind": "git";
  /**
   * Tag, branch, or commit ref
   */
  "ref"?: string;
  "url": string;
} | {
  "kind": "internal";
} | {
  "kind": "local";
  "path": string;
};

export interface DeploymentHealthEventPayload {
  "failure_count": number;
  "port_lease_id"?: null | string;
  "previous_ready": boolean;
  "probe": DeploymentHealthProbe;
  "ready": boolean;
  "reason": string;
  "route_id": string;
}

export interface DeploymentHealthProbe {
  "kind": string;
}

export interface DeploymentReconcileSummary {
  "execs_failed": number;
  "leases_promoted": number;
  "leases_released": number;
  "routes_promoted": number;
  "routes_removed": number;
}

export type EmptyParams = Record<string, unknown>;

export type EntryDescriptor = {
  "abi_version": number;
  "crate_ref": string;
  "kind": "rust_inproc";
  "symbol": string;
} | {
  "abi_version": number;
  "kind": "wasm";
  "memory_limit_mb": number;
  "module": string;
} | {
  "auth": RemoteAuth;
  "endpoint": string;
  "kind": "remote";
} | {
  "bundle": string;
  "kind": "surface_bundle";
} | {
  "command": Array<string>;
  "kind": "subprocess";
  "transport"?: SubprocessTransport;
};

export interface ErrorShape {
  "code": string;
  "details": unknown;
  "message": string;
}

export interface EventEnvelope {
  "id": string;
  "kind": string;
  "metadata"?: unknown;
  "payload": unknown;
  "schema_version": number;
  "sequence": number;
  "session_id": string;
  "timestamp": string;
  "writer_package_id": string;
}

export interface EventListRequest {
  "after_sequence"?: null | number;
  "kind_prefix"?: null | string;
  "limit"?: null | number;
  "session_id": string;
  "writer_package_id"?: null | string;
}

export type EventListResult = Array<{
  "id": string;
  "kind": string;
  "metadata"?: unknown;
  "payload": unknown;
  "schema_version": number;
  "sequence": number;
  "session_id": string;
  "timestamp": string;
  "writer_package_id": string;
}>;

export interface EventPermissions {
  "append"?: boolean;
  "read"?: boolean;
}

export type EventSubscribeResult = null;

export interface ExecCommand {
  "args"?: Array<string>;
  "program": string;
}

export type ExecCompletedPayload = Record<string, unknown>;

export type ExecDeniedPayload = Record<string, unknown>;

export type ExecFailedPayload = Record<string, unknown>;

export interface ExecIdParams {
  "exec_id": string;
}

export type ExecLifecyclePolicy = "stop_on_session_close" | "keep_alive" | "stop_on_idle";

export type ExecRequestPayload = Record<string, unknown>;

export interface ExecResourceLimits {
  "max_cpu_millis"?: null | number;
  "max_duration_ms"?: null | number;
  "max_log_bytes"?: null | number;
  "max_memory_mb"?: null | number;
}

export type ExecStartedPayload = Record<string, unknown>;

export interface ExecStatus {
  "exec_id"?: null | string;
  "exit_code"?: null | number;
  "kind": ExecStatusKind;
  "message"?: null | string;
  "ready": boolean;
  "target_id"?: null | string;
}

export type ExecStatusKind = "pending" | "running" | "stopped" | "exited" | "failed" | "denied" | "unknown";

export type ExecStoppedPayload = Record<string, unknown>;

export interface ExecutionTarget {
  "capabilities"?: Array<ExecutionTargetCapability>;
  "id": string;
  "name": string;
  "reachability": ExecutionTargetReachability;
  "status": ExecutionTargetStatusKind;
}

export type ExecutionTargetCapability = "local_exec" | "port_lease" | "http_proxy_upstream" | "websocket_proxy_upstream";

export type ExecutionTargetReachability = "local_host";

export type ExecutionTargetStatusKind = "available" | "unavailable";

/**
 * The kind of outbound executor that produced a response.
 */
export type ExecutorKind = "deny_all" | "fake" | "real";

export type ExtensionPointDescribeResult = null;

export interface ExtensionPointDescriptor {
  "id": string;
  "modifiable": boolean;
  "payload_schema"?: unknown;
  "short_circuit": boolean;
  "timing": HookTiming;
  "version": string;
}

export type ExtensionPointListResult = Array<string>;

export interface FilesystemPermissions {
  "read"?: Array<string>;
  "write"?: Array<string>;
}

export type FrameKind = "text" | "binary";

export interface HandleLease {
  "expires_at"?: null | string;
  "invocations_used": number;
  "max_invocations"?: null | number;
}

export interface HandleProvenance {
  "granted_at": string;
  /**
   * "kernel" if minted by kernel itself.
   */
  "granted_by_package_id": string;
  /**
   * e.g. "auto_mint", "package_load", "attenuate", "delegate".
   */
  "via_method": string;
}

export interface HandleScope {
  "holder_package_id": string;
  "session_id"?: null | string;
}

export type HookListResult = Array<{
  "subscriber_package_id": string;
  "subscription": HookSubscription;
}>;

export interface HookSubscription {
  "extension_point": string;
  "handler": string;
  "precedence"?: number;
  "timing": HookTiming;
}

export type HookTiming = "sync" | "async";

export type HostDiagnosticsResult = Record<string, unknown>;

export interface HostInfo {
  "methods": Array<ProtocolMethod>;
  "protocol_version": string;
  "supported_transports": Array<string>;
}

export interface HostPingResult {
  "ok": true;
}

export type HostPrincipalResult = null;

/**
 * Response returned by `kernel.v1.outbound.stream` on the initial call.
 * 
 * Contains the stream_id for subscribing to events, the start status, and metadata about the executor that will handle the stream.
 */
export interface KernelOutboundStreamResponse {
  /**
   * What kind of executor is handling the stream.
   */
  "executor_kind": ExecutorKind;
  /**
   * Whether real network I/O will be performed.
   */
  "network_performed": boolean;
  /**
   * Redaction state applied to stream frames.
   */
  "redaction_state"?: RedactionState;
  /**
   * Whether the stream started successfully.
   */
  "status": StreamStartStatus;
  /**
   * The stream_id to subscribe to for stream frames.
   */
  "stream_id": string;
}

export interface KernelSession {
  "active_package_set": Array<string>;
  "created_at": string;
  "id": string;
  "labels": Array<string>;
  "metadata"?: unknown;
  "principal_scope"?: null | string;
  "status": SessionStatus;
  "updated_at": string;
}

export interface LocalExecDeclaration {
  "max_count"?: null | number;
  "programs"?: Array<string>;
  "target_id": string;
}

export interface LocalExecListResponse {
  "executions": Array<ExecStatus>;
}

export interface LocalExecLogLine {
  "message_redacted": string;
  "seq": number;
  "stream": LocalExecLogStream;
}

export type LocalExecLogStream = "stdout" | "stderr" | "system";

export interface LocalExecLogsRequest {
  "exec_id": string;
  "limit"?: null | number;
  "since_seq"?: null | number;
}

export interface LocalExecLogsResponse {
  "error"?: null | string;
  "exec_id": string;
  "lines": Array<LocalExecLogLine>;
  "next_seq"?: null | number;
}

export interface LocalExecPermissions {
  "declarations"?: Array<LocalExecDeclaration>;
  "max_count"?: null | number;
}

export interface LocalExecStartRequest {
  "command": ExecCommand;
  /**
   * Required by the live executor. Fake/deny executors tolerate omission for backwards-compatible protocol fixtures.
   */
  "cwd"?: null | string;
  /**
   * Explicit environment to pass to the child. The live executor clears the inherited environment and forwards only keys allowed by host policy.
   */
  "env"?: Record<string, string>;
  "lifecycle"?: ExecLifecyclePolicy;
  "port_names"?: Array<string>;
  "readiness_probe"?: ReadinessProbe;
  "resource_limits"?: ExecResourceLimits;
  "target_id": string;
}

export interface LocalExecStartResponse {
  "error"?: null | string;
  "exec_id"?: null | string;
  "status": ExecStatus;
}

export interface LocalExecStatusResponse {
  "error"?: null | string;
  "status": ExecStatus;
}

export interface LocalExecStopRequest {
  "exec_id": string;
  "reason"?: null | string;
}

export interface LocalExecStopResponse {
  "error"?: null | string;
  "exec_id": string;
  "status": ExecStatus;
}

export type MethodStatus = "implemented" | "partial" | "planned";

/**
 * A single network access declaration in a package manifest.
 * 
 * Each entry describes an allowed outbound destination with host, permitted HTTP methods, and a human-readable purpose. The runtime / host policy checker matches outbound requests against declared entries. Packages with no `network` declarations must not make any outbound network requests.
 */
export interface NetworkDeclaration {
  /**
   * Destination host (e.g. `"api.openai.com"` or `"*.example.org"`).
   */
  "host": string;
  /**
   * Permitted HTTP/WebSocket methods (e.g. `["GET", "POST", "WEBSOCKET"]`). Empty means all.
   */
  "methods"?: Array<string>;
  /**
   * Human-readable purpose for this network access.
   */
  "purpose"?: null | string;
}

export interface NetworkPermissions {
  /**
   * Structured network declarations (host, methods, purpose).
   */
  "declarations"?: Array<NetworkDeclaration>;
  /**
   * Flat host list for backward compatibility. Packages using the structured form should populate `declarations` instead.
   */
  "hosts"?: Array<string>;
}

export interface OpenSessionRequest {
  "active_package_set": Array<string>;
  "labels": Array<string>;
  "metadata": unknown;
}

export interface OutboundAuditParams {
  "package_id": string;
}

/**
 * Generic outbound audit record / envelope.
 * 
 * Records an outbound network request made by a package through Ygg-provided network/request helpers. This is a kernel event payload — it does NOT contain raw secrets, bodies, headers, prompts, or responses. Only `secret_ref` identifiers and the `redaction_state` are recorded.
 */
export interface OutboundAuditRecord {
  /**
   * Capability through which the request was made.
   */
  "capability_id": string;
  /**
   * Cost placeholder.
   */
  "cost"?: unknown;
  /**
   * Destination host.
   */
  "destination_host": string;
  /**
   * Error message if status is not "allowed".
   */
  "error"?: null | string;
  /**
   * Unique record id.
   */
  "id": string;
  /**
   * HTTP method (GET, POST, etc).
   */
  "method": string;
  /**
   * Package that owns the outbound request.
   */
  "package_id": string;
  /**
   * The principal that initiated the request.
   */
  "principal": string;
  /**
   * Declared purpose from the manifest or request context.
   */
  "purpose"?: null | string;
  /**
   * Redaction state — what data, if any, was recorded.
   */
  "redaction_state"?: RedactionState;
  /**
   * Secret references used (not raw secrets).
   */
  "secret_refs_used"?: Array<string>;
  /**
   * Request status: "allowed", "denied", "error", etc.
   */
  "status": string;
  /**
   * Usage placeholder (e.g. token count).
   */
  "usage"?: unknown;
}

export type OutboundAuditResult = Array<{
  /**
   * Capability through which the request was made.
   */
  "capability_id": string;
  /**
   * Cost placeholder.
   */
  "cost"?: unknown;
  /**
   * Destination host.
   */
  "destination_host": string;
  /**
   * Error message if status is not "allowed".
   */
  "error"?: null | string;
  /**
   * Unique record id.
   */
  "id": string;
  /**
   * HTTP method (GET, POST, etc).
   */
  "method": string;
  /**
   * Package that owns the outbound request.
   */
  "package_id": string;
  /**
   * The principal that initiated the request.
   */
  "principal": string;
  /**
   * Declared purpose from the manifest or request context.
   */
  "purpose"?: null | string;
  /**
   * Redaction state — what data, if any, was recorded.
   */
  "redaction_state"?: RedactionState;
  /**
   * Secret references used (not raw secrets).
   */
  "secret_refs_used"?: Array<string>;
  /**
   * Request status: "allowed", "denied", "error", etc.
   */
  "status": string;
  /**
   * Usage placeholder (e.g. token count).
   */
  "usage"?: unknown;
}>;

export type OutboundExecuteCompletedPayload = Record<string, unknown>;

export interface OutboundExecuteParams {
  "body_shape": unknown;
  "capability_id": string;
  "destination_host": string;
  "metadata": unknown;
  "method": string;
  "package_id"?: null | string;
  "path"?: null | string;
  "purpose"?: null | string;
  "secret_headers": Array<OutboundSecretHeaderSpec>;
  "secret_refs": Array<string>;
  "static_headers": Array<OutboundStaticHeader>;
  "timeout_ms"?: null | number;
}

/**
 * Response returned by an outbound executor.
 * 
 * Like the request, this is content-free. It carries status, the *shape* of headers/body, usage/cost placeholders, and metadata identifying what kind of executor produced the response.
 */
export interface OutboundExecutorResponse {
  /**
   * JSON *shape* of the response body.
   */
  "body_shape"?: unknown;
  /**
   * Cost placeholder (e.g. `{"total_cost_usd": 0.002}`).
   */
  "cost"?: unknown;
  /**
   * What kind of executor produced this response.
   */
  "executor_kind": ExecutorKind;
  /**
   * JSON *shape* of the response headers (e.g. `{"content-type": "application/json", "x-ratelimit-remaining": "..."}`).
   */
  "headers_shape"?: unknown;
  /**
   * Whether real network I/O was performed.
   */
  "network_performed": boolean;
  /**
   * Provider-assigned request id (e.g. `req-abc123`).
   */
  "provider_request_id"?: null | string;
  /**
   * Redaction state applied to the response.
   */
  "redaction_state"?: RedactionState;
  /**
   * High-level status: "ok", "error", "denied", "timeout".
   */
  "status": string;
  /**
   * HTTP-style status code if applicable (e.g. 200, 429, 503).
   */
  "status_code"?: null | number;
  /**
   * Usage placeholder (e.g. `{"prompt_tokens": 10, "completion_tokens": 20}`).
   */
  "usage"?: unknown;
}

/**
 * Specification for a secret-derived HTTP header to be injected by the host during outbound execution. Packages declare these in `kernel.v1.outbound.execute` params as `secret_headers`; the host resolves the `secret_ref` at execution time and injects the resulting header value into the live HTTP request.
 * 
 * Raw secret values never appear in audit, response, or Debug output.
 */
export interface OutboundSecretHeaderSpec {
  "header_name": string;
  "scheme": string;
  "secret_ref": string;
}

/**
 * A safe non-secret static header for outbound requests (L5).
 * 
 * Only header names on the `STATIC_HEADER_ALLOWLIST` are permitted. Secret-bearing header names (Authorization, x-api-key, Cookie, etc.) are rejected at parse time. Values must be plain strings that do not look like raw secrets.
 */
export interface OutboundStaticHeader {
  "name": string;
  "value": string;
}

export interface OutboundStreamParams {
  "body_shape": unknown;
  "capability_id": string;
  "destination_host": string;
  "max_duration_ms"?: null | number;
  "max_frame_bytes"?: null | number;
  "max_total_bytes"?: null | number;
  "metadata": unknown;
  "method": string;
  "package_id"?: null | string;
  "path"?: null | string;
  "purpose"?: null | string;
  "secret_headers": Array<OutboundSecretHeaderSpec>;
  "secret_refs": Array<string>;
  "static_headers": Array<OutboundStaticHeader>;
  "stream_format"?: StreamFormat | null;
  "timeout_ms"?: null | number;
}

/**
 * Summary of a completed outbound stream, returned by the executor.
 */
export interface OutboundStreamSummary {
  /**
   * JSON shape of the response body (redacted preview).
   */
  "body_shape"?: unknown;
  /**
   * Total bytes received.
   */
  "bytes_received": number;
  /**
   * What kind of executor produced this summary.
   */
  "executor_kind": ExecutorKind;
  /**
   * Total number of frames emitted.
   */
  "frame_count": number;
  /**
   * JSON shape of response headers (redacted).
   */
  "headers_shape"?: unknown;
  /**
   * Whether real network I/O was performed.
   */
  "network_performed": boolean;
  /**
   * Provider-assigned request id if available.
   */
  "provider_request_id"?: null | string;
  /**
   * Redaction state applied to the stream.
   */
  "redaction_state"?: RedactionState;
  /**
   * Final status: "ok", "error", "timeout", "cancelled".
   */
  "status": string;
  /**
   * HTTP status code if available.
   */
  "status_code"?: null | number;
}

/**
 * Request to open a WebSocket connection.
 */
export interface OutboundWebSocketOpenRequest {
  "capability_id": string;
  "destination_host": string;
  "max_duration_ms": number;
  "max_frame_bytes": number;
  "max_idle_ms": number;
  "max_total_bytes_inbound": number;
  "max_total_bytes_outbound": number;
  "metadata": unknown;
  "package_id": string;
  "path"?: null | string;
  "purpose"?: null | string;
  "secret_headers": Record<string, string>;
  "secret_refs": Array<string>;
  /**
   * Pre-resolved headers (raw); secrets injected in handshake. Static-only.
   */
  "static_headers": Record<string, string>;
  "subprotocols": Array<string>;
}

export interface OutboundWebSocketSendParams {
  "bytes"?: Array<number> | null;
  "code"?: null | number;
  "connection_id": string;
  "data"?: null | string;
  "kind"?: FrameKind | null;
  "reason"?: null | string;
}

export type OutboundWebsocketCloseResult = Record<string, unknown>;

export type OutboundWebsocketCompletedPayload = Record<string, unknown>;

export type OutboundWebsocketErrorPayload = Record<string, unknown>;

export type OutboundWebsocketFramePayload = Record<string, unknown>;

export type OutboundWebsocketOpenResult = Record<string, unknown>;

export type OutboundWebsocketOpenedPayload = Record<string, unknown>;

export type OutboundWebsocketSendResult = Record<string, unknown>;

export interface PackageAuditReport {
  "declared": DeclaredAuthority;
  "package_id": string;
  "since": string;
  "suggestions": Array<TighteningSuggestion>;
  "until": string;
  "unused": UnusedAuthority;
  "used": UsedAuthority;
}

export interface PackageContributions {
  "extension_points"?: Array<ExtensionPointDescriptor>;
  "hooks"?: Array<HookSubscription>;
  "schemas"?: Array<SchemaContribution>;
  "surfaces"?: Array<SurfaceContribution>;
}

export interface PackageDependency {
  /**
   * Logical package id (must match the dependency's manifest.id once resolved)
   */
  "id": string;
  /**
   * Optional: GPG public key fingerprints required to sign this dep If empty, no signature verification required If set, the dep's GPG-signed tag must be signed by one of these
   */
  "minimum_signed_by"?: Array<string>;
  /**
   * Where the package comes from
   */
  "source": DependencySource;
  /**
   * Semver constraint (e.g., ">=1.0.0", "^2.1", "=1.2.3") Empty string means "any version"
   */
  "version"?: string;
}

export type PackageDescribeResult = null;

export interface PackageFailureSummary {
  "exit_code"?: null | string;
  "failed_at": string;
  "log_tail_redacted": Array<SubprocessLogLine>;
  "package_id": string;
  "reason": string;
  "redaction_state": RedactionState;
  "signal"?: null | string;
  "state": PackageState;
  "stderr_tail_redacted": Array<string>;
  "stderr_truncated": boolean;
}

export interface PackageIdParams {
  "package_id": string;
}

export interface PackageLifecyclePayload {
  "capability_count": number;
  /**
   * Contract mode selected by the package entry. `none` marks Path B: a self-contained app hosted without contract enforcement.
   */
  "contract_mode": ContractMode;
  "entry_kind": string;
  "extension_point_count": number;
  "hook_count": number;
  "package_id": string;
  "reason"?: null | string;
  "state": string;
  "version": string;
}

export type PackageListResult = Array<{
  "capability_count": number;
  "entry_kind": string;
  "extension_point_count": number;
  "hook_count": number;
  "id": string;
  "last_failure"?: PackageFailureSummary | null;
  "loaded_at": string;
  "manifest": PackageManifest;
  "state": PackageState;
  "trust_level": TrustLevel;
  "updated_at": string;
  "version": string;
}>;

export type PackageLogsResult = Array<{
  "line": string;
  "package_id": string;
  "stream": string;
}>;

export interface PackageManifest {
  "author"?: null | string;
  "consumes"?: Array<CapabilityRequirement>;
  "contributes"?: PackageContributions;
  "description"?: null | string;
  "display_name"?: null | string;
  "entry": EntryDescriptor;
  "id": string;
  "license"?: null | string;
  "permissions"?: PermissionSet;
  "provides"?: Array<CapabilityDescriptor>;
  /**
   * First-class package dependency declarations. Distinct from `consumes` (which declares capability requirements). Empty by default for backward compat.
   */
  "requires"?: Array<PackageDependency>;
  "sandbox_policy"?: SandboxPolicy;
  "schema_version": number;
  "version": string;
}

export interface PackageManifest2 {
  "author"?: null | string;
  "consumes"?: Array<CapabilityRequirement>;
  "contributes"?: PackageContributions;
  "description"?: null | string;
  "display_name"?: null | string;
  "entry": EntryDescriptor;
  "id": string;
  "license"?: null | string;
  "permissions"?: PermissionSet;
  "provides"?: Array<CapabilityDescriptor>;
  /**
   * First-class package dependency declarations. Distinct from `consumes` (which declares capability requirements). Empty by default for backward compat.
   */
  "requires"?: Array<PackageDependency>;
  "sandbox_policy"?: SandboxPolicy;
  "schema_version": number;
  "version": string;
}

export interface PackagePermissions {
  "call"?: Array<string>;
}

export interface PackageRecord {
  "capability_count": number;
  "entry_kind": string;
  "extension_point_count": number;
  "hook_count": number;
  "id": string;
  "last_failure"?: PackageFailureSummary | null;
  "loaded_at": string;
  "manifest": PackageManifest;
  "state": PackageState;
  "trust_level": TrustLevel;
  "updated_at": string;
  "version": string;
}

export type PackageState = "discovered" | "loading" | "starting" | "ready" | "degraded" | "stopping" | "stopped" | "unloaded";

export type PermissionAuditResult = Array<{
  "id": string;
  "kind": string;
  "metadata"?: unknown;
  "payload": unknown;
  "schema_version": number;
  "sequence": number;
  "session_id": string;
  "timestamp": string;
  "writer_package_id": string;
}>;

export interface PermissionDeniedPayload {
  "operation"?: string;
  "package_id"?: string;
}

export interface PermissionGrantParams {
  "permission": string;
  "principal": ProtocolPrincipal;
  "reason"?: null | string;
  "scope"?: null | string;
}

export interface PermissionGrantRecord {
  "granted_at": string;
  "id": string;
  "permission": string;
  "principal": ProtocolPrincipal;
  "reason"?: null | string;
  "revoked_at"?: null | string;
  "scope"?: null | string;
}

export interface PermissionListParams {
  "principal"?: ProtocolPrincipal | null;
}

export type PermissionListResult = Array<{
  "granted_at": string;
  "id": string;
  "permission": string;
  "principal": ProtocolPrincipal;
  "reason"?: null | string;
  "revoked_at"?: null | string;
  "scope"?: null | string;
}>;

export interface PermissionRevokeParams {
  "grant_id": string;
}

export interface PermissionSet {
  "assets"?: AssetPermissions;
  "capabilities"?: CapabilityPermissions;
  "events"?: EventPermissions;
  "filesystem"?: FilesystemPermissions;
  "local_exec"?: LocalExecPermissions;
  "network"?: NetworkPermissions;
  "packages"?: PackagePermissions;
  "ports"?: PortPermissions;
  "proxy"?: ProxyPermissions;
  /**
   * Declared secret references this package may use in `kernel.v1.outbound.execute` calls. Each entry must be a valid env-backed secret reference (e.g. `secret_ref:env:OPENAI_API_KEY`, `secretRef:env:MY_KEY`, `secret-ref:env:NAME`, `host:env:NAME`).
   * 
   * The runtime enforces fail-closed: any `secret_ref` used in `secret_headers` or top-level `secret_refs` at dispatch time **must** appear in this list, or the request is denied.
   * 
   * Default: empty vec (no secret refs allowed; backward compatible).
   */
  "secret_refs"?: Array<string>;
}

export interface PermissionSet2 {
  "assets"?: AssetPermissions;
  "capabilities"?: CapabilityPermissions;
  "events"?: EventPermissions;
  "filesystem"?: FilesystemPermissions;
  "local_exec"?: LocalExecPermissions;
  "network"?: NetworkPermissions;
  "packages"?: PackagePermissions;
  "ports"?: PortPermissions;
  "proxy"?: ProxyPermissions;
  /**
   * Declared secret references this package may use in `kernel.v1.outbound.execute` calls. Each entry must be a valid env-backed secret reference (e.g. `secret_ref:env:OPENAI_API_KEY`, `secretRef:env:MY_KEY`, `secret-ref:env:NAME`, `host:env:NAME`).
   * 
   * The runtime enforces fail-closed: any `secret_ref` used in `secret_headers` or top-level `secret_refs` at dispatch time **must** appear in this list, or the request is denied.
   * 
   * Default: empty vec (no secret refs allowed; backward compatible).
   */
  "secret_refs"?: Array<string>;
}

export type PortBindScope = "loopback_only";

export interface PortDeclaration {
  "max_count"?: null | number;
  "port_names"?: Array<string>;
  "target_id": string;
}

export type PortDeniedPayload = Record<string, unknown>;

export interface PortLeaseIdParams {
  "lease_id": string;
}

export interface PortLeaseRecord {
  "bind": PortBindScope;
  "host": string;
  "id": string;
  "port": number;
  "port_name": string;
  "protocol": PortProtocol;
  "status": PortLeaseStatusKind;
  "target_id": string;
}

export interface PortLeaseRecord2 {
  "bind": PortBindScope;
  "host": string;
  "id": string;
  "port": number;
  "port_name": string;
  "protocol": PortProtocol;
  "status": PortLeaseStatusKind;
  "target_id": string;
}

export interface PortLeaseRequest {
  "port_name": string;
  "protocol"?: PortProtocol;
  "requested_port"?: null | number;
  "target_id": string;
}

export interface PortLeaseResponse {
  "lease": PortLeaseRecord;
}

export type PortLeaseStatusKind = "active" | "reserved" | "released";

export type PortLeasedPayload = Record<string, unknown>;

export type PortListResult = Array<{
  "bind": PortBindScope;
  "host": string;
  "id": string;
  "port": number;
  "port_name": string;
  "protocol": PortProtocol;
  "status": PortLeaseStatusKind;
  "target_id": string;
}>;

export interface PortPermissions {
  "declarations"?: Array<PortDeclaration>;
  "max_count"?: null | number;
}

export type PortProtocol = "tcp" | "udp";

export type PortReleasedPayload = Record<string, unknown>;

export type ProjectGetResult = {
  /**
   * The actual project content.
   */
  "project": ProjectInner;
  /**
   * Schema version. Currently always 1.
   */
  "schema_version": number;
};

export interface ProjectIdParams {
  "project_id": string;
}

export interface ProjectLifecyclePayloadSchema {
  "new_state": ProjectState;
  "previous_state"?: ProjectState | null;
  "project_id": string;
  "title": string;
  "type": ProjectType;
}

export interface ProjectListItemSchema {
  "description": string;
  "entry_surface_id"?: null | string;
  "icon"?: null | string;
  "id": string;
  "running_session_id": string;
  "state": ProjectState;
  "storage_summary"?: ProjectStorageSummarySchema | null;
  "title": string;
  "type": ProjectType;
}

export interface ProjectListParams {
  "filter_state"?: ProjectState | null;
}

export interface ProjectListResultSchema {
  "projects": Array<ProjectListItemSchema>;
}

export interface ProjectStartResult {
  "already_running": boolean;
  "new_state": ProjectState;
  "previous_state": ProjectState;
  "project_id": string;
  "session_id": string;
}

/**
 * Runtime project state. Not serialized to project.yaml; tracked by registry.
 */
export type ProjectState = "archived" | "failed" | "installed" | "running" | "starting" | "stopped" | "stopping";

export interface ProjectStatusResult {
  "project_id": string;
  "running_session_id": string;
  "secrets_count": number;
  "sessions_count": number;
  "state": ProjectState;
  "storage_summary"?: ProjectStorageSummarySchema | null;
}

export interface ProjectStopResult {
  "new_state": ProjectState;
  "previous_state": ProjectState;
  "project_id": string;
  "session_id": string;
}

export interface ProjectStorageSummarySchema {
  "bundle_bytes"?: null | number;
  "cache_bytes"?: null | number;
  "data_bytes"?: null | number;
  "log_bytes"?: null | number;
  "measured_at"?: null | string;
  "measurement_state": StorageMeasurementStateSchema;
  "total_bytes"?: null | number;
}

export type ProjectType = "external_workspace" | "external_wrapped" | "yggdrasil_native";

export interface ProjectionDefinition {
  "id": string;
  "session_id": string;
  "source_kind_prefix"?: null | string;
  "state"?: unknown;
}

export interface ProjectionIdParams {
  "projection_id": string;
}

export type ProjectionListResult = Array<{
  "id": string;
  "session_id": string;
  "source_kind_prefix"?: null | string;
  "state"?: unknown;
}>;

export interface ProposalApproval {
  "decided_at": string;
  "principal": ProtocolPrincipal;
  "reason"?: null | string;
}

export interface ProposalDecisionParams {
  "proposal_id": string;
  "reason"?: null | string;
}

export interface ProposalIdParams {
  "proposal_id": string;
}

export type ProposalListResult = Array<{
  "approval"?: ProposalApproval | null;
  "created_at"?: string;
  "created_by"?: ProtocolPrincipal;
  "expected_effects"?: unknown;
  "id"?: string;
  "operations"?: Array<ProposalOperation>;
  "required_permissions"?: Array<string>;
  "result"?: unknown;
  "status"?: ProposalStatus;
  "target_branch_id"?: null | string;
  "target_session_id"?: null | string;
}>;

export interface ProposalOperation {
  "op": string;
  "payload"?: unknown;
  "target"?: null | string;
}

export interface ProposalRecord {
  "approval"?: ProposalApproval | null;
  "created_at"?: string;
  "created_by"?: ProtocolPrincipal;
  "expected_effects"?: unknown;
  "id"?: string;
  "operations"?: Array<ProposalOperation>;
  "required_permissions"?: Array<string>;
  "result"?: unknown;
  "status"?: ProposalStatus;
  "target_branch_id"?: null | string;
  "target_session_id"?: null | string;
}

export type ProposalStatus = "created" | "approved" | "rejected" | "applied" | "failed";

export interface ProtocolContext {
  "correlation_id"?: null | string;
  "parent_invocation_id"?: null | string;
  "principal": ProtocolPrincipal;
  /**
   * Optional kernel session id this call is operating under. Used by outbound dispatch to scope secret resolution to the session's project.
   */
  "session_id"?: null | string;
  "transport": string;
}

export interface ProtocolMethod {
  "id": string;
  "status": MethodStatus;
  "streaming": boolean;
}

export type ProtocolPrincipal = {
  "assistant_id": string;
  "delegated_user_id"?: null | string;
  "kind": "assistant";
} | {
  "kind": "anonymous";
} | {
  "kind": "host_admin";
} | {
  "kind": "host_dev";
} | {
  "kind": "human";
  "user_id": string;
} | {
  "kind": "package";
  "package_id": string;
};

export interface ProxyDeclaration {
  "max_count"?: null | number;
  "route_ids"?: Array<string>;
}

export type ProxyDeniedPayload = Record<string, unknown>;

export type ProxyListResult = Array<{
  "id": string;
  "iframe_url": string;
  "protocol": ProxyProtocol;
  "public_url": string;
  "ready": boolean;
  "status": ProxyRouteStatusKind;
  "upstream": ProxyRouteUpstream;
}>;

export interface ProxyPermissions {
  "declarations"?: Array<ProxyDeclaration>;
  "max_count"?: null | number;
}

export type ProxyProtocol = "http" | "websocket";

export type ProxyRegisteredPayload = Record<string, unknown>;

export interface ProxyRouteIdParams {
  "route_id": string;
}

export interface ProxyRouteRecord {
  "id": string;
  "iframe_url": string;
  "protocol": ProxyProtocol;
  "public_url": string;
  "ready": boolean;
  "status": ProxyRouteStatusKind;
  "upstream": ProxyRouteUpstream;
}

export interface ProxyRouteRecord2 {
  "id": string;
  "iframe_url": string;
  "protocol": ProxyProtocol;
  "public_url": string;
  "ready": boolean;
  "status": ProxyRouteStatusKind;
  "upstream": ProxyRouteUpstream;
}

export interface ProxyRouteRegisterRequest {
  "protocol"?: ProxyProtocol;
  "route_id"?: null | string;
  "upstream": ProxyRouteUpstream;
}

export interface ProxyRouteRegisterResponse {
  "route": ProxyRouteRecord;
}

export type ProxyRouteStatusKind = "active" | "stale" | "removed";

export interface ProxyRouteUpstream {
  "port_lease_id": string;
  "port_name": string;
}

export type ProxyUnregisteredPayload = Record<string, unknown>;

export interface ReadinessProbe {
  "initial_delay_ms"?: null | number;
  "kind": ReadinessProbeKind;
  "path"?: null | string;
  "port_name"?: null | string;
  "timeout_ms"?: null | number;
}

export type ReadinessProbeKind = "none" | "tcp_port" | "http_get";

/**
 * Redaction state for an outbound audit record.
 * 
 * Every outbound request carries one of these states to indicate whether raw body/header/prompt/response data was preserved. The default is `NotCaptured` — raw data is never saved unless explicitly approved.
 */
export type RedactionState = "explicitly_approved" | "not_captured" | "policy_ref" | "redacted" | "unsafe_blocked";

export interface RemoteAuth {
  "config"?: unknown;
  "scheme": string;
}

export interface SandboxPolicy {
  "cpu_quota_ms_per_invoke"?: number;
  "memory_mb"?: number;
  "wall_clock_ms"?: number;
}

export interface SchemaContribution {
  "id": string;
  "schema": unknown;
}

export interface SessionBranchListParams {
  "session_id": string;
}

export type SessionBranchListResult = Array<{
  "child_session_id": string;
  "created_at": string;
  "forked_from_sequence": number;
  "id": string;
  "metadata"?: unknown;
  "parent_session_id": string;
}>;

export interface SessionCloseParams {
  "session_id": string;
}

export type SessionClosedPayload = Record<string, unknown>;

export interface SessionForkParams {
  "forked_from_sequence": number;
  "metadata": unknown;
  "parent_session_id": string;
}

export interface SessionGetParams {
  "session_id": string;
}

export type SessionListResult = null;

export type SessionOpenedPayload = Record<string, unknown>;

export type SessionStatus = "open" | "closed";

export type StorageMeasurementStateSchema = "measured" | "unknown";

/**
 * The format of a streaming response for `kernel.v1.outbound.stream`.
 */
export type StreamFormat = "ndjson" | "raw" | "sse";

/**
 * Generic stream frame envelope — the unit of streaming capability output.
 * 
 * This is a content-free protocol shape. It carries invocation/stream identifiers, sequencing, and redaction state, but no model, prompt, agent, or message semantics. The `payload` field is opaque JSON controlled by the capability provider.
 */
export interface StreamFrameEnvelope {
  /**
   * Frame type discriminant.
   */
  "frame_type": StreamFrameType;
  /**
   * The invocation this frame belongs to.
   */
  "invocation_id": string;
  /**
   * Opaque metadata — capability-provider-defined.
   */
  "metadata"?: unknown;
  /**
   * Opaque payload — capability-provider-defined; no kernel content semantics. May be `Null` for progress/end/cancelled/timeout frames.
   */
  "payload"?: unknown;
  /**
   * Redaction state applied to the payload.
   */
  "redaction_state"?: RedactionState;
  /**
   * Monotonically increasing sequence within this stream.
   */
  "sequence": number;
  /**
   * Unique stream id (may differ from invocation_id if a capability produces multiple concurrent streams).
   */
  "stream_id": string;
  /**
   * Timestamp of frame emission.
   */
  "timestamp"?: string;
}

/**
 * The type of a stream frame — content-free, no model/prompt semantics.
 */
export type StreamFrameType = "cancelled" | "chunk" | "end" | "error" | "progress" | "start" | "timeout";

/**
 * Status returned when a streaming outbound request starts.
 */
export type StreamStartStatus = "denied" | "error" | "ok";

export type StreamStartedPayload = Record<string, unknown>;

export interface SubprocessLogLine {
  "line": string;
  "package_id": string;
  "stream": string;
}

export type SubprocessTransport = "json_rpc_stdio" | "json_rpc_tcp";

export interface SurfaceActivation {
  "input_schema"?: unknown;
  "launch_capability_id"?: null | string;
  "session_template"?: unknown;
}

export type SurfaceApprovalPolicy = "none" | "user_approval" | "fork_then_approve";

export type SurfaceBundleSourceSchema = "installed_project" | "dev_path";

export interface SurfaceContribution {
  "activation"?: SurfaceActivation;
  /**
   * Additional exact capability ids this surface bundle may invoke through the web surface bridge. This is a typed declaration; bridge policy must not infer invoke authority from opaque metadata.
   */
  "allowed_capability_ids"?: Array<string>;
  "approval_policy"?: SurfaceApprovalPolicy | null;
  "capability_id"?: null | string;
  "description"?: null | string;
  "id": string;
  "metadata"?: unknown;
  "required_permissions"?: Array<SurfacePermissionRequirement>;
  "slot": SurfaceSlot;
  "title": string;
  "version"?: string;
}

export type SurfaceContributionDescribeResult = Record<string, unknown>;

export type SurfaceContributionListResult = Array<unknown>;

export interface SurfaceDescribeParams {
  "surface_id": string;
}

export interface SurfaceListParams {
  "slot"?: null | string;
}

export interface SurfacePermissionRequirement {
  "permission": string;
  "reason"?: null | string;
  "risk"?: SurfaceRisk;
  "scope"?: null | string;
}

export interface SurfaceResolveBundleParams {
  "surface_id": string;
}

export interface SurfaceResolveBundleResult {
  "bundle_url": string;
  "export_name": string;
  "project_id"?: null | string;
  "source": SurfaceBundleSourceSchema;
  "stylesheets": Array<string>;
  "surface_id": string;
  "wrapper_class"?: null | string;
}

export type SurfaceRisk = "low" | "medium" | "high";

export type SurfaceSlot = "experience_entry" | "home_card" | "quick_action" | "workshop_card" | "play_renderer" | "forge_panel" | "asset_editor" | "assistant_action";

export interface TargetIdParams {
  "target_id": string;
}

export type TargetListResult = Array<{
  "capabilities"?: Array<ExecutionTargetCapability>;
  "id": string;
  "name": string;
  "reachability": ExecutionTargetReachability;
  "status": ExecutionTargetStatusKind;
}>;

export interface TighteningSuggestion {
  "kind": string;
  "rationale": string;
  "target": string;
}

export type TrustLevel = "trusted_inproc" | "process_isolated" | "wasm_sandbox" | "remote_boundary" | "static_surface";

export interface UnusedAuthority {
  "capabilities_unused": Array<string>;
  "network_hosts_unused": Array<string>;
  "secret_refs_unused": Array<string>;
}

export interface UsedAuthority {
  "assets_read_count": number;
  "assets_write_count": number;
  "capabilities_invoked": Record<string, number>;
  "events_append_count": number;
  "events_read_count": number;
  "network_hosts_used": Record<string, number>;
  "secret_refs_used": Record<string, number>;
}
