use std::fs;
use std::path::PathBuf;
use std::sync::Arc;

use anyhow::Result;
use serde_json::json;
use ygg_runtime::{
    CapabilityInvocationRequest, InMemoryEventStore, Runtime, RuntimeConfig,
};

use super::manifest::read_manifest;
use crate::templates;

pub(crate) async fn package_load(path: PathBuf) -> Result<()> {
    let manifest = read_manifest(path).await?;
    let store = Arc::new(InMemoryEventStore::default());
    let runtime = Runtime::new(store, RuntimeConfig::default());
    let record = runtime.load_package(manifest).await?;
    println!("loaded package: {}@{} ({:?})", record.id, record.version, record.state);
    Ok(())
}

pub(crate) async fn package_check(path: PathBuf) -> Result<()> {
    let manifest = read_manifest(path).await?;
    manifest.validate_basic()?;
    println!("package check: {}@{} ok", manifest.id, manifest.version);
    Ok(())
}

pub(crate) async fn package_run_fixture(path: PathBuf) -> Result<()> {
    let manifest = read_manifest(path).await?;
    let store = Arc::new(InMemoryEventStore::default());
    let runtime = Runtime::new(store, RuntimeConfig::default());
    let record = runtime.load_package(manifest).await?;
    println!("package fixture ready: {} ({:?})", record.id, record.state);
    Ok(())
}

pub(crate) async fn package_invoke_local(path: PathBuf, capability_id: String, input: String) -> Result<()> {
    let manifest = read_manifest(path).await?;
    let payload: serde_json::Value = serde_json::from_str(&input)?;
    let store = Arc::new(InMemoryEventStore::default());
    let runtime = Runtime::new(store, RuntimeConfig::default());
    runtime.load_package(manifest).await?;
    let result = runtime
        .invoke_capability(CapabilityInvocationRequest { capability_id, caller_package_id: None, provider_package_id: None, version: None, input: payload })
        .await?;
    println!("{}", serde_json::to_string_pretty(&result)?);
    Ok(())
}

pub(crate) async fn package_conformance(path: PathBuf) -> Result<()> {
    let manifest = read_manifest(path).await?;
    manifest.validate_basic()?;
    let capability = manifest
        .provides
        .first()
        .ok_or_else(|| anyhow::anyhow!("package conformance requires at least one provided capability"))?
        .id
        .clone();
    let store = Arc::new(InMemoryEventStore::default());
    let runtime = Runtime::new(store, RuntimeConfig::default());
    runtime.load_package(manifest).await?;
    let result = runtime
        .invoke_capability(CapabilityInvocationRequest {
            capability_id: capability,
            caller_package_id: None,
            provider_package_id: None,
            version: None,
            input: json!({"package_conformance": true}),
        })
        .await?;
    anyhow::ensure!(result.output == json!({"package_conformance": true}), "package did not echo conformance payload");
    println!("package conformance: ok");
    Ok(())
}

pub(crate) async fn init_package(path: PathBuf, id: String, entry: String, language: String) -> Result<()> {
    fs::create_dir_all(&path)?;
    let package_py = path.join("package.py").display().to_string();
    let package_mjs = path.join("package.mjs").display().to_string();
    let is_typescript = language.starts_with("typescript");
    let subprocess_command = if is_typescript {
        format!("    - node\n    - {package_mjs}")
    } else {
        format!("    - python3\n    - {package_py}")
    };
    let surfaces = if language.contains("experience") {
        format!(
            r#"  surfaces:
    - id: {id}/entry
      version: 0.1.0
      slot: experience_entry
      title: Generated Experience
      description: Launchable package entry generated by ygg init-package.
      capability_id: {id}/echo
      activation:
        launch_capability_id: {id}/echo
        session_template:
          labels: [generated, experience]
      approval_policy: user_approval
    - id: {id}/play
      version: 0.1.0
      slot: play_renderer
      title: Generated Play Renderer
      capability_id: {id}/echo
    - id: {id}/forge
      version: 0.1.0
      slot: forge_panel
      title: Generated Forge Panel
      capability_id: {id}/echo
    - id: {id}/assist
      version: 0.1.0
      slot: assistant_action
      title: Generated Assistant Action
      capability_id: {id}/echo
      approval_policy: fork_then_approve
"#
        )
    } else {
        "  surfaces: []\n".to_string()
    };
    let manifest = match entry.as_str() {
        "wasm" => format!(
            r#"schema_version: 1
id: {id}
version: 0.1.0
entry:
  kind: wasm
  module: package.wasm
  abi_version: 1
  memory_limit_mb: 64
provides: []
consumes: []
contributes:
  schemas: []
  hooks: []
  extension_points: []
  surfaces: []
permissions: {{}}
sandbox_policy:
  cpu_quota_ms_per_invoke: 5000
  memory_mb: 64
  wall_clock_ms: 30000
"#
        ),
        "remote" => format!(
            r#"schema_version: 1
id: {id}
version: 0.1.0
entry:
  kind: remote
  endpoint: https://example.invalid/ygg/package
  auth:
    scheme: none
    config: null
provides: []
consumes: []
contributes:
  schemas: []
  hooks: []
  extension_points: []
  surfaces: []
permissions: {{}}
sandbox_policy:
  cpu_quota_ms_per_invoke: 5000
  memory_mb: 128
  wall_clock_ms: 30000
"#
        ),
        "subprocess" => format!(
            r#"schema_version: 1
id: {id}
version: 0.1.0
entry:
  kind: subprocess
  command:
{subprocess_command}
  transport: json_rpc_stdio
provides:
  - id: {id}/echo
    version: 0.1.0
    input_schema: {{}}
    output_schema: {{}}
    streaming: false
consumes: []
contributes:
  schemas: []
  hooks: []
  extension_points: []
{surfaces}
permissions: {{}}
sandbox_policy:
  cpu_quota_ms_per_invoke: 5000
  memory_mb: 128
  wall_clock_ms: 30000
"#
        ),
        _ => format!(
            r#"schema_version: 1
id: {id}
version: 0.1.0
entry:
  kind: rust_inproc
  crate_ref: package-crate
  symbol: register
  abi_version: 1
provides: []
consumes: []
contributes:
  schemas: []
  hooks: []
  extension_points: []
  surfaces: []
permissions: {{}}
sandbox_policy:
  cpu_quota_ms_per_invoke: 5000
  memory_mb: 128
  wall_clock_ms: 30000
"#
        ),
    };
    fs::write(path.join("manifest.yaml"), manifest)?;
    if entry == "subprocess" && language.starts_with("python") {
        fs::write(path.join("package.py"), templates::PYTHON_SUBPROCESS_TEMPLATE)?;
    } else if entry == "subprocess" && is_typescript {
        fs::write(path.join("package.ts"), templates::typescript_subprocess_template(&id))?;
        fs::write(path.join("package.mjs"), templates::TYPESCRIPT_SUBPROCESS_RUNTIME_TEMPLATE)?;
        fs::write(path.join("tsconfig.json"), templates::TYPESCRIPT_TSCONFIG)?;
        fs::write(path.join("package.json"), templates::typescript_package_json(&id))?;
    }
    fs::write(
        path.join("README.md"),
        format!("# {id}\n\nYggdrasil capability package skeleton.\n\nRun `ygg package conformance manifest.yaml` from this directory.\n"),
    )?;
    println!("initialized package skeleton at {}", path.display());
    Ok(())
}
